{
 "title": "JVM metrics (InfluxDB)",
 "description": "Metrics from MyPerf4J stored in InfluxDB v1.x",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": "SHOW TAG VALUES FROM jvm_memory_metrics_v2 WITH KEY = \"AppName\""
   },
   {
    "name": "DC",
    "query": "SHOW TAG VALUES FROM jvm_memory_metrics_v2 WITH KEY = \"dc\" WHERE AppName =~ /^$Application$/ "
   },
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM jvm_memory_metrics_v2  WITH KEY = \"host\" WHERE AppName =~ /^$Application$/ "
   }
  ]
 },
 "panels": [
  {
   "title": "JVM GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "YoungGC Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"java_lang_G1_Young_Generation_CollectionCount\")\r\n",
     "select": [
      [
       { "params": [ "YoungGcCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "YoungGC Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"java_lang_G1_Young_Generation_CollectionTime\")\r\n",
     "select": [
      [
       { "params": [ "YoungGcTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "FullGC Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_gc_collection_seconds_count\" )\r\n",
     "select": [
      [
       { "params": [ "FullGcCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "FullGC Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_gc_collection_seconds_sum\" )",
     "select": [
      [
       { "params": [ "FullGcTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Eden Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_memory_pool_bytes_used\" and r.pool==\"G1 Eden Space\")\r\n",
     "select": [
      [
       { "params": [ "EdenUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "Eden Used Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r.pool == \"G1 Eden Space\" and (r._field == \"jvm_memory_pool_bytes_used\" or r._field == \"jvm_memory_pool_bytes_max\"))\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({ _time: r._time, _value: r.jvm_memory_pool_bytes_used / r.jvm_memory_pool_bytes_max * 100.0 }))\r\n",
     "select": [
      [
       { "params": [ "EdenUsedPercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "Survivor Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_memory_pool_bytes_used\" and r.pool==\"G1 Survivor Space\")\r\n",
     "select": [
      [
       { "params": [ "SurvivorUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "Survivor Used Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r.pool == \"G1 Survivor Space\" and (r._field == \"jvm_memory_pool_bytes_used\" or r._field == \"jvm_memory_pool_bytes_max\"))\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({ _time: r._time, _value: r.jvm_memory_pool_bytes_used / r.jvm_memory_pool_bytes_max * 100.0 }))\r\n",
     "select": [
      [
       { "params": [ "SurvivorUsedPercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "OldGen Used Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "select": [
      [
       { "params": [ "OldGenUsedPercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_memory_bytes_used\" and r.area == \"heap\" )\r\n",
     "select": [
      [
       { "params": [ "HeapUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap Used Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r.area == \"heap\" and (r._field == \"jvm_memory_bytes_used\" or r._field == \"jvm_memory_bytes_max\"))\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({ _time: r._time, _value: r.jvm_memory_bytes_used / r.jvm_memory_bytes_max * 100.0 }))\r\n",
     "select": [
      [
       { "params": [ "HeapUsedPercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "OldGen Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "select": [
      [
       { "params": [ "OldGenUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "CodeCache Used Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "select": [
      [
       { "params": [ "CodeCacheUsedPercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "NonHeap Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_memory_bytes_used\" and r.area == \"nonheap\" )",
     "select": [
      [
       { "params": [ "NonHeapUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "NonHeap Used Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r.area == \"nonheap\" and (r._field == \"jvm_memory_bytes_used\" or r._field == \"jvm_memory_bytes_max\"))\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({ r with _value: r.jvm_memory_bytes_used / r.jvm_memory_bytes_max }))\r\n",
     "select": [
      [
       { "params": [ "NonHeapUsedPercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "CodeCache Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "select": [
      [
       { "params": [ "CodeCacheUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "Metaspace Used Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r.pool == \"Metaspace\" and (r._field == \"jvm_memory_pool_bytes_used\" or r._field == \"jvm_memory_pool_bytes_max\"))\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({ r with _value: r.jvm_memory_pool_bytes_used / r.jvm_memory_pool_bytes_max }))\r\n",
     "select": [
      [
       { "params": [ "MetaspaceUsedPercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "PermGen Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "select": [
      [
       { "params": [ "PermGenUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "PermGen Used Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "select": [
      [
       { "params": [ "PermGenUsedPercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "Metaspace Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_memory_pool_bytes_used\" and r.pool == \"Metaspace\" )",
     "select": [
      [
       { "params": [ "MetaspaceUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pool Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_buffer_pool_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_buffer_pool_used_buffers\" )\r\n",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "PoolName", "operator": "=", "value": "direct" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pool Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_buffer_pool_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_buffer_pool_used_bytes\" )",
     "select": [
      [
       { "params": [ "MemoryUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "PoolName", "operator": "=", "value": "direct" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pool Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_buffer_pool_metrics_v2",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_buffer_pool_capacity_bytes\" )\r\n  ",
     "select": [
      [
       { "params": [ "MemoryCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=~", "value": "/^$DC$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "PoolName", "operator": "=", "value": "direct" }
     ]
    }
   ]
  },
  {
   "title": "JVM Thread",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Thread",
   "type": "graph",
   "description": "当前存活的线程数，包括守护线程和非守护线程",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_thread_metrics",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_threads_state\" and r.state==\"RUNNABLE\")",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Runnable Thread",
   "type": "graph",
   "description": "正在JVM中执行的线程",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_thread_metrics",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_threads_state\" and r.state==\"RUNNABLE\")",
     "select": [
      [
       { "params": [ "Runnable" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "TimedWating  Thread",
   "type": "graph",
   "description": "等待另一个线程来执行取决于指定等待时间的操作的线程数",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_thread_metrics",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_threads_state\" and r.state==\"TIMED_WAITING\")\r\n  ",
     "select": [
      [
       { "params": [ "TimedWaiting" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Wating  Thread",
   "type": "graph",
   "description": "无限期地等待另一个线程来执行某一特定操作的线程数",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_thread_metrics",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_threads_state\" and r.state==\"WAITING\")",
     "select": [
      [
       { "params": [ "Waiting" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Blocked Thread",
   "type": "graph",
   "description": "受阻塞并等待某个监视器锁的线程数",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_thread_metrics",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"jvm_threads_state\" and r.state==\"BLOCKED\")\r\n",
     "select": [
      [
       { "params": [ "Blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM File Descriptor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Open Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_file_descriptor_metrics",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"java_lang_OperatingSystem_OpenFileDescriptorCount\")",
     "select": [
      [
       { "params": [ "OpenCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Open Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_file_descriptor_metrics",
     "query": "  from(bucket: v.bucket)\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._field == \"java_lang_OperatingSystem_OpenFileDescriptorCount\" or r._field == \"java_lang_OperatingSystem_MaxFileDescriptorCount\")\r\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> map(fn: (r) => ({ _time: r._time, _value: r.java_lang_OperatingSystem_OpenFileDescriptorCount / r.java_lang_OperatingSystem_MaxFileDescriptorCount * 100.0 }))\r\n",
     "select": [
      [
       { "params": [ "OpenPercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Compilation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_compilation_metrics",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"java_lang_Compilation_CompilationTimeMonitoringSupported\")",
     "select": [
      [
       { "params": [ "Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_compilation_metrics",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"java_lang_Compilation_TotalCompilationTime\")",
     "select": [
      [
       { "params": [ "TotalTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM ClassLoading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Class",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_class_metrics",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"java_lang_ClassLoading_LoadedClassCount\")\r\n  ",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Loaded Class",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_class_metrics",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"java_lang_ClassLoading_TotalLoadedClassCount\")\r\n  ",
     "select": [
      [
       { "params": [ "Loaded" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Unloaded Class",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jvm_class_metrics",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"java_lang_ClassLoading_UnloadedClassCount\")\r\n  ",
     "select": [
      [
       { "params": [ "Unloaded" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "AppName", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  }
 ]
}