---
version: "3.7"
services:
  prometheus:
    image: prom/prometheus:v2.39.1
    volumes:
      - ./conf/:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway" #TODO: proper network on WSL
  pushgateway:
    image: prom/pushgateway:v1.4.3
    volumes:
      - ./conf/:/etc/prometheus/
    command:
      - --web.config.file=/etc/prometheus/pushgateway.yml
    ports:
      - "9091:9091"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  influxdb1:
    image: influxdb:1.9.0
    ports:
      - '8086:8086'
    volumes:
      - influxdb1-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_HTTP_HTTPS_ENABLED=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles:
      - dontstart
  telegraf:
    image: telegraf:1.24.3
    volumes:
      - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb2
    ports:
      - '8125:8125'
      - '1234:1234'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  influxdb2: # http://host.docker.internal:8086
    #curl --request POST "http://localhost:8086/api/v2/write?org=artipie&bucket=abucket&precision=ns"   --header "Authorization: Token randomAdminInitTokenValue"   --header "Content-Type: text/plain; charset=utf-8"   --header "Accept: application/json"   --data-binary 'devices,dev=1 value=2.2,value2=3.3' 
    image: influxdb:2.5.1
    ports:
      - "8086:8086"
    volumes:
      - influxdb2-config:/etc/influxdb2
      - influxdb2-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=artipie
      - DOCKER_INFLUXDB_INIT_BUCKET=abucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=randomAdminInitTokenValue
    extra_hosts:
      - "host.docker.internal:host-gateway"
  chronograf:
    image: chronograf:1.9.4
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb2
    environment:
      - INFLUXDB_URL=http://host.docker.internal:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    extra_hosts:
    - "host.docker.internal:host-gateway"
  grafana:
  # from(bucket: "abucket") |> range(start: -1h)
    image: grafana/grafana:9.2.4
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./grafana-dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb2
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  artipie-test:
    image: artipie/artipie:v0.28.0
    volumes:
      - "./var_artipie:/var/artipie"
      - "./conf:/etc/artipie"
    user: "0:0"
    # curl -v -X PUT -u "github.com/ChGen:token" http://localhost:8080/ChGen/bintest/test.dat --data "abc123"
    # curl -v -X PUT http://localhost:8080/chgen/bintest/test.dat --data "abc123"
    environment:
      - JVM_ARGS=
        -javaagent:/etc/artipie/jmx_prometheus_javaagent-0.17.2.jar=${JMX_AGENT}:/etc/artipie/jmx-agent.yml
        -agentlib:jdwp=transport=dt_socket,server=y,address=*:${JDEBUG},suspend=n -Djava.rmi.server.hostname=localhost 
        -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=${JMX_PORT} 
        -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} -Dcom.sun.management.jmxremote.local.only=false 
        -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
    ports:
      - "8080:8080"
      - "8087:8087" #vertx metrics
      - "${JDEBUG}:${JDEBUG}"
      - "${JMX_PORT}:${JMX_PORT}"
      - "${JMX_AGENT}:${JMX_AGENT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #profiles:
    #  - dontstart
volumes:
  influxdb1-storage:
  influxdb2-config:
  influxdb2-data:
  chronograf-storage:
  grafana-storage:
