# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    monitor: "artipie"
remote_write:
   - url: "http://host.docker.internal:1234/receive"
  #- url: "http://host.docker.internal:8086/api/v1/prom/write?db=prometheus" #influxdb1
     basic_auth:
       username: admin
       password: admin
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    basic_auth:
      username: admin
      password: admin
    static_configs:
      - targets: ["localhost:9090"]
      
  - job_name: "pushgateway"
    static_configs:
      - targets: ["host.docker.internal:9091"]
    basic_auth:
      username: admin
      password: admin

  - job_name: "artipie_jvm_metrics"
    static_configs:
      - targets: ["host.docker.internal:12345"]
      
  - job_name: "artipie_metrics"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: "/prometheus/metrics"

  - job_name: "artipie_vertx_metrics"
    static_configs:
      - targets: ["host.docker.internal:8087"]
